### ISSUE TITLE
fetlife username begins with a hyphen i.e: "-slave"

### ISSUE THREAD

**Issue by annabel82** [meitar/fetlife-export#2]
If your username begins with a hyphen and you type: 

./fetlife-export.pl -yourusername

The program will produce an error saying "Unknown option: yourusername" because it thinks
that -yourusername is a command of some sort. To get around that type this:

./fetlife-export.pl -- -yourusername

That's
dot forwardslash fetlife-export.pl space hyphen hyphen space -yourusername

Hope this helps someone x

**Comment by meitar** [comment]
Ah, yes, thanks for pointing that out. I'll add a note about this to the readme.

**Comment by annahowell** [comment]
Add

cpan Term::ReadKey

too x
